version: '3.1'
services:
  stats-server:
    build: stats-server/stats-service
    container_name: stats-server-image
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_STATS=jdbc:postgresql://stats-db:5432/EWMStats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=EWMStats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root